/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import javax.crypto.*;
import javax.crypto.spec.GCMParameterSpec;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.security.*;
import java.security.cert.CertificateException;
import java.security.interfaces.RSAPublicKey;
import java.util.Arrays;
import java.util.Base64;
import java.util.Enumeration;
import java.nio.file.Files;


public class App {
    public static Provider ensurePKCSImplementation(String configfilePath){
        Provider sunPkcs11 = Security.getProvider("SunPKCS11");
        Provider pkcsImplementation = sunPkcs11.configure(configfilePath);

        if (pkcsImplementation != null) {
            System.out.println("PKCS implementation is not null");
            Security.addProvider(pkcsImplementation);
            return pkcsImplementation;
        }
        throw new RuntimeException("No PKCS Implementation found");
    }


    public static void main(String[] args) {

        try {
            String configFilePath = "/home/dimitri/Documents/HSLU/BAA/thesis_preliminary/java_only/pkcs11.cfg";
            String userPin = "123456789"; // The pin to unlock the HSM-TOKEN
            String keyID = "7777"; // The key identifier or alias
            String keyAlias="rsaGenesis";

            Provider pkcsImplementation=ensurePKCSImplementation(configFilePath);


            KeyStore hsmKeyStore = KeyStore.getInstance("PKCS11", pkcsImplementation);

            // load keystore and log in
            hsmKeyStore.load(null, userPin.toCharArray());

            RSAPublicKey publicKey = (RSAPublicKey)hsmKeyStore.getCertificate(keyAlias).getPublicKey();
            System.out.println(publicKey);

            Enumeration<String> e =hsmKeyStore.aliases();
            while (e.hasMoreElements()){
                System.out.println(e.nextElement());
            }


        }catch (KeyStoreException | IOException | NoSuchAlgorithmException | CertificateException e){
            System.out.println(e);}

    }}
