/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.io.IOException;
import java.security.*;
import java.security.cert.CertificateException;
import java.util.Arrays;
import java.util.Enumeration;


public class App {
    public static void main(String[] args) {

        try {
            String configuration = "/home/dimitri/Documents/HSLU/BAA/thesis_preliminary/java_only/pkcs11.cfg";
            String userPin = "123456789"; // The pin to unlock the HSM-TOKEN
            String keyID = "3333"; // The key identifier or alias
            String keyAlias="MyFirstAESKey";

            Provider sunPkcs11 = Security.getProvider("SunPKCS11");
            Provider pkcsImplementation = sunPkcs11.configure(configuration);

            if (pkcsImplementation != null) {
                System.out.println("PKCS implementation is not null");
            }

            Security.addProvider(pkcsImplementation);

            KeyStore hsmKeyStore = KeyStore.getInstance("PKCS11", pkcsImplementation);

            hsmKeyStore.load(null, userPin.toCharArray());

            // AES-Variant works because RSA NEEDS a certificate!

            hsmKeyStore.getKey(keyAlias, userPin.toCharArray());
            Key k= hsmKeyStore.getKey(keyAlias, userPin.toCharArray());

            //NEXT STEPS:
            // Encrypt on SoftHSM/Feed Data to SoftHSM and return result
            // Do it asymetrically as well
            // proper logging (SLF4J etc. )


        }catch (KeyStoreException|IOException|NoSuchAlgorithmException| CertificateException|UnrecoverableKeyException e){
            System.out.println(e);
        }

}}
